### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by raaron773** [lxgr-linux/pokete#108]
**Checklist**
I have:
- [x ] Searched the Issues page for my problem/feature request
- [ x] Updated all related software and Pokete it self

**Describe the bug**
Won't run, I get this error:

Traceback (most recent call last):
  File "./pokete/pokete.py", line 1735, in <module>
    logging.basicConfig(filename=log_file,
  File "/usr/lib64/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

**To Reproduce**
unable to run
just `./pokete/pokete.py` gives me the above error

**Expected behavior**
Should 

**Screenshots**

**Environment**
 - OS: OpenSUSE Tumbleweed
 - Pokete version: 0.6.0
 - Python version: 3.10
 - Scrap engine version: 1.2.0

**Comment by RayBB** [comment]
I get the same issue when running via gitpod:
gitpod.io/#https://github.com/lxgr-linux/pokete

**Comment by BatCountry** [comment]
> Traceback (most recent call last): File "./pokete/pokete.py", line 1735, in logging.basicConfig(filename=log_file, File "/usr/lib64/**python3.8**/logging/**init**.py", line 2009, in basicConfig raise ValueError('Unrecognised argument(s): %s' % keys) ValueError: Unrecognised argument(s): encoding
>     * **Python version: 3.10**

Looks like you've got a python environment problem - you're effectively still using Python 3.8, not 3.10.  The  encoding argument was added in Python 3.9.

For a workaround, it may be easier to set up a virtual environment with 3.10 to run the game.

Try `python3.10 -m venv ./poketepy` in the pokete directory, then source the `activate` script in the `poketepy/bin` directory that gets created. (for any Windows users who read this, run the `activate.bat` in the `Scripts` subdirectory of that `poketepy` directory that the python command created).

**Comment by kotx** [comment]
For Gitpod users (or people with `pyenv`), just run `pyenv install 3.10.2 && pyenv local 3.10.2 && python ./pokete.py`

**Comment by mendhak** [comment]
On Ubuntu 20.04, 

    sudo apt install python3.9-venv
    python3.9 -m venv ./poketepy

**Comment by lxgr-linux** [comment]
Another way to ensure the right python version is by using `pipenv`:
```
pipenv install
pipenv run ./pokete.py
```

This also installs the needed dependencies.
I should maybe add to the README that this is possible.

**Comment by raaron773** [comment]
just using `python3.10 ./pokete.py` also works.
Thank you!
