### ISSUE TITLE
Fight with next pokemon when the previous dies

### ISSUE THREAD

**Issue by diego-rapoport** [lxgr-linux/pokete#109]
**Is your feature request related to a problem? Please describe.**
Well, I really don't like to have a fight with a pokemon, lose it, and then I cannot use another one I own to continue the fight.

**Describe the solution you'd like**
Just be able to choose another pokemon to fight when the last one died. Just like the original game.

I'd like to thank for the game so far!! Enjoying it a lot.

**Comment by lxgr-linux** [comment]
Thank's a lot, all the great feedback I got for this is really flattering,
I will implement this as soon as possible.
Greetings
