### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by qqqays** [lxgr-linux/pokete#114]
**Checklist**
I have:
- [ y] Searched the Issues page for my problem/feature request
- [ y] Updated all related software and Pokete it self

**Describe the bug**
  File "pokete.py", line 166
    if (index := deck(6, "Your deck", True)) is None:
              ^
SyntaxError: invalid syntax

**To Reproduce**
1. install required packages
2. run pokete.py

**Expected behavior**
run up

**Screenshots**
![image](https://user-images.githubusercontent.com/22659021/159611621-f305227e-e260-464f-b2f5-e1b069aa754d.png)

**Environment**
 - OS: [ windows10]
 - Pokete version [master brach]
 - Python version [3.7]
 - Scrap engine version [1.2.0]

**Additional context**

**Comment by Wang-haoran** [comment]
you can run this with this command: sudo python3.8 pokete.py
of course, python 3.x is indeed

**Comment by lxgr-linux** [comment]
Since you're on windows just upgrading to python 3.10 would fix this problem.

**Comment by qqqays** [comment]
> Since you're on windows just upgrading to python 3.10 would fix this problem.

ok, it works.
and this project can not run in pycharm
