### ISSUE TITLE
in game keys still on terminal after exit

### ISSUE THREAD

**Issue by marco-gallegos** [lxgr-linux/pokete#124]
**Checklist**
I have:
- [x] Searched the Issues page for my problem/feature request
- [x] Updated all related software and Pokete it self

**Describe the bug**
when i close the game all the keys i pushed in the game still on terminal after close.

**To Reproduce**
1. open game
2. play a little
3. quit game

**Expected behavior**
i dont want to see any in game keys after close game.

**Screenshots**
![image](https://user-images.githubusercontent.com/6290032/163698529-6a5d856f-b2a5-43d4-a3da-7c9e87902b0f.png)

**Environment**
 - OS: mac osx monterrey
 - Pokete version: master branch
 - Python version: 3.9
 - Scrap engine version: i dont know
 - default os terminal

**Additional context**
NA

**Comment by lxgr-linux** [comment]
Hello, thanks for your report,
I already encountered this happening on windows, but to prevent this from happening on OSX, I fist have to research if and how the tty and termios modules work on OSX.

**Comment by denisstrizhkin** [comment]
The same thing happens when I play.

os: openbsd
term: xterm
python: Python 3.9.13

Package      Version
------------ -------
playsound    1.3.0
pycairo      1.21.0
PyGObject    3.42.1
pynput       1.7.6
python3-xlib 0.15
scrap-engine 1.2.0
six          1.16.0

**Comment by lxgr-linux** [comment]
I still have to verify if the input buffer method will work on MacOS and therefore BSD, but I don't have a Mac laying around to test this.
I will look at BSD in a VM though.
