### ISSUE TITLE
PC stuck on first level.

### ISSUE THREAD

**Issue by brendencallahan** [lxgr-linux/pokete#131]
**Checklist**
I have:
- [ x] Searched the Issues page for my problem/feature request
- [ x] Updated all related software and Pokete it self

**Describe the bug**
Player character is stuck on first level. Even after beating first npc and catching poketes still unable to move outside of original boundary.

**To Reproduce**
1. Fresh install of scrap_engine, python3, and pokete
2. run $ git clone 'url'
3. run $ ./pokete/pokete.py
4. unable to progress past first fight. (screen does not scroll/move when getting to edges)

**Expected behavior**
Expect more of the map to appear as suggested when hitting (3).

**Environment**
 - OS: [Ubuntu 22.04]
 - Pokete version [0.7.2]
 - Python version [3.10.4]
 - Scrap engine version [unknown] (installed on June 10, 2022)

**Additional context**
Using alacritty 0.11.0 minimized.

Feel free to close if I just missed the intended method of progression.

**Comment by brendencallahan** [comment]
Scrap engine was installed on June 10, 2022 so it was the current version at the time of writing.

**Comment by skylarmt** [comment]
Have you tried the cave at the top of town?  I agree, many of the warp points are really hard to find.

**Comment by brendencallahan** [comment]
> Have you tried the cave at the top of town? Mny of the warp points are really hard to find. I got stuck a little while before I hit on the right spot by chance.

Found it! Wow, that was difficult. Maybe a marker or different color is in order. Thanks for the help and I love this project!

**Comment by lxgr-linux** [comment]
This is something that has to be fixed in #127.

**Comment by chewi** [comment]
I've been gaming for many years, and I didn't even realise that was a cave. I thought it was the edge of a river or something. I don't think I'd have figured it out if I hadn't come here.

**Comment by lxgr-linux** [comment]
#127 will make this may more obvious.
