### ISSUE TITLE
Can't free poketes

### ISSUE THREAD

**Issue by cognivore** [lxgr-linux/pokete#136]
**Checklist**
I have:
- [x] Searched the Issues page for my problem/feature request
- [x] Updated all related software and Pokete it self

**Describe the bug**
When you have five poketes, the game crashes when you try to free one. I commented out the code which is supposed to re-pack the deck and the crash disappeared. The error was "NoneType" has no attribute and something about balls.

**To Reproduce**
1. Get 5 poketes
2. Open deck
3. Free a pokete
4. Game crashes

**Expected behavior**

**Screenshots**

**Environment**
 - OS: [e.g. Linux]
 - Pokete version [e.g. 1.1.0]
 - Python version [e.g. 3.10.1]
 - Scrap engine version [e.g. 1.1.0]

**Additional context**

**Comment by lxgr-linux** [comment]
That's really good to know, this bug must have been introduced in the more recent code cleaning attempts.
I fixed it, and thanks a lot for pointing this out.
