### ISSUE TITLE
Use $XDG_STATE_HOME for storing state

### ISSUE THREAD

**Issue by rhbvkleef** [lxgr-linux/pokete#137]
Pokete's gamesave is stored in `~/.cache`, which is not an appropriate path for storing such data. The author probably meant to use `$XDG_CACHE_HOME` which usually resolves to  the same path. However, according to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), we should use `$XDG_STATE_HOME`. Alternatively "If $XDG_STATE_HOME is either not set or empty, a default equal to $HOME/.local/state should be used" (the spec).

Alternatively, Pokete could introduce a configuration file (stored in `$XDG_CONFIG_HOME` or `$XDG_CONFIG_DIRS`) in which we can configure the path where the gamesave is stored. Another alternative would be to introduce a command-line flag.

The why: `~/.cache` is periodically cleaned up by some users (including me), so storing essential data there is incredibly inconvenient, and also isn't appropriate according to the XDG Base Directory Specification, stating "the base directory relative to which user-specific non-essential data files should be stored".

**Comment by lxgr-linux** [comment]
Hello, I think this is a good idea, but I would use `$XDG_DATA_HOME` instead.
