### ISSUE TITLE
Roll for initiative

### ISSUE THREAD

**Issue by cognivore** [lxgr-linux/pokete#143]
**Is your feature request related to a problem? Please describe.**
It's rather unfortunate that by picking a high INI pokete I can more or less guarantee being able to run away from poketes of a comparable level.

**Describe the solution you'd like**
I would like for the right of the first move to be randomised. I'm not sure about the formula, but something like random(1, 15) + Initiative could skew the probabilities just enough.

**Comment by lxgr-linux** [comment]
Yes, I think a bit more randomization would be helpful in that case.
Another possibility would be to add a probability of failing to run away, so that running through the map and always running away from the enemy won't be possible so easily.
