### ISSUE TITLE
Diagonal Movement

### ISSUE THREAD

**Issue by abdowns** [lxgr-linux/pokete#151]
In the game, I can not hold two directional movement keys at once to move in a diagonal line. This isn't very pleasant when navigating around the map. Please implement this; if you don't I will do it myself via pull request.

**Comment by lxgr-linux** [comment]
By the nature of the input buffer I'm not really sure if this is possible at all, but it would be nice to see how you would implement it.

Regards

**Comment by Dagonali** [comment]
When I remember correctly old Pokemon games did not have Diagonal movement.     
At first when I played Pokete it felt a little strange, but only because I wasn't used to it anymore. I like it that way.    
Maybe this could be a mod?

**Comment by abdowns** [comment]
I think I'll start work on a pull request with this. Shouldn't be too hard to implement. It can be an optional feature that is toggled on and off.

**Comment by lxgr-linux** [comment]
I'm really looking forward to you implementing this.

**Comment by abdowns** [comment]
I don't really care about it anymore sorry

**Comment by lxgr-linux** [comment]
So I will close this.
