### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by Izaic** [lxgr-linux/pokete#152]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Battle sounds and ambient music added to the game

**Comment by abdowns** [comment]
Pulse audio

**Comment by lxgr-linux** [comment]
I would love to add audio, but the problem is, that I first need some audio files to add to the game. And I'm not a very musical person.

**Comment by laurinneff** [comment]
Maybe you could make the code and some "programmer art" audio for now so when someone who is capable of making proper audio comes along they'd just have to replace those audio files?

**Comment by abdowns** [comment]
Yeah, there are some really easy-to-use sites that are meant for non-musically inclined programmers to make 8-bit style music for their games. You could easily whip something up within minutes,

**Comment by sandraev** [comment]
Maybe I can suggest you the [music made by Eric Skiff](https://ericskiff.com/music/)... the album is named "Resistor Anthem", and even if this title doesn't really match the spirit of your game, the musics are just wonderful ! Take a look !

**Comment by gitofbabai** [comment]
I just created a small piece of audio file [ .WAV] so attaching a zipped file. Please tell me if this is helpful.
[game.zip](https://github.com/lxgr-linux/pokete/files/8919103/game.zip)
.

**Comment by lxgr-linux** [comment]
Music is on the way!


> Maybe I can suggest you the [music made by Eric Skiff](https://ericskiff.com/music/)... the album is named "Resistor Anthem", and even if this title doesn't really match the spirit of your game, the musics are just wonderful ! Take a look !

I think this really fit's the game, especially for the different regions.
I found more music here: https://xdeviruchi.itch.io/8-bit-fantasy-adventure-music-pack that I'll use for the battles.
