### ISSUE TITLE
Pokete should be on itch.io

### ISSUE THREAD

**Issue by 173duprot** [lxgr-linux/pokete#154]
[itch.io](https://itch.io/) is a FOSS-supporting indi game platform. I think that it would be very cool to buy it from you over there.

It's one of the few FOSS platforms that has a culture of actually paying it's developers. And this is exactly the type of game that I'm looking for over there < 3.

**Comment by SephirothWS** [comment]
https://itch.io/docs/general/about

itchio is not a FOSS platform, and is actually a for-profit company.

**Comment by MaFeLP** [comment]
Pokete is actually on itch.io (<https://lxgr-linux.itch.io/pokete>), it just hasn't been updated since version 0.3.2...

**Comment by lxgr-linux** [comment]
I may go in and update it.

**Comment by lxgr-linux** [comment]
I updated itch.io page.
