### ISSUE TITLE
Both i.hp <= 0

### ISSUE THREAD

**Issue by Mingy123** [lxgr-linux/pokete#158]
**Checklist**
I have:
- [*] Searched the Issues page for my problem/feature request
- [*] Updated all related software and Pokete it self

**Describe the bug**
IndexError when both pokete are at hp 0, possible due to effects such as burning and poison.
Caused by `winner = [i for i in players if i.hp > 0][0]`

**To Reproduce**
1. Run ./pokete.py
2. In a match, end with both pokete at hp 0

**Expected behavior**
The game crashes to the terminal with python error IndexError

**Environment**
 - OS: Artix 5.18.2
 - Pokete version 0.7.2
 - Python version 3.10.5
 - Scrap engine version 1.2.0

**Comment by lxgr-linux** [comment]
I think I have to build in some fallback condition, that in this case the player always wins or nobody. But good to know that those edgecases occur.

**Comment by Dagonali** [comment]
I'd suggest it's a draft, that makes it so that the player gets another try against this enemy and has to maybe get a little stronger.
