### ISSUE TITLE
Able to Free All Pokete

### ISSUE THREAD

**Issue by Jacenu** [lxgr-linux/pokete#159]
**Checklist**
I have:
- [ *] Searched the Issues page for my problem/feature request
- [ *] Updated all related software and Pokete it self

**Describe the bug**
The game allows you to free all pokete from your deck which breaks encounters. If you enter an encounter with no pokete the only action you can take is to run, if you manage to do try anything else the game will crash.

**To Reproduce**
1. open your "deck" and press "free" for all pokete

**Expected behavior**
the game ought limit limit you from freeing your last pokete.

**Environment**
 - OS: [Void 5.15.45]
 - Pokete version [ 0.7.2]
 - Python version [3.10.5]
 - Scrap Engine version [1.2.0]

**Comment by lxgr-linux** [comment]
Oh yes,
that's pretty bad.
I didn't think of such an edgecase.
Thanks for reporting this.
