### ISSUE TITLE
Glitched commandprompt

### ISSUE THREAD

**Issue by Bambaclad1** [lxgr-linux/pokete#162]
**Checklist**
I have:
- [x] Searched the Issues page for my problem/feature request
- [x] Updated all related software and Pokete it self

**Describe the bug**
I just open pokete.py and the commandprompt looks weird,
It also pops up a random error notification
![image](https://user-images.githubusercontent.com/67043806/173903818-5b3985fc-6c5b-4fec-9028-0e0582f2b6ff.png)

**Environment**
 - OS: Windows 10
 - Pokete version 0.72
 - Python version 3.10 (From MSStore)
 - Scrap engine version 1.20

**Comment by MaFeLP** [comment]
Hi!

Sadly, Microsoft does not enable escape codes by default in the Command Prompt and users have to set a specific Registry-Key to enable them. Below you should find a detailed description:

1. Press and hold the windows-key, next to your Ctrl-key.
1. Press the letter `R` on your keyboard.
1. Release both keys.
1. Empty the box, that popped up in the bottom left corner of your screen.
1. If it is empty, type `regedit` and then press `OK`.
1. If asked a user control prompt, click `Yes`.
1. In the Registry window, you should see a bar on the left hand side, like the one in your explorer. In there, navigate to the folder `Computer\HKEY_CURRENT_USER\Console`.
1. On the right hand side of the window, you should now see many values, having in it `ColorTable00`, `ColorTable01`, etc.
1. In the empty white space on the right/middle of this window, make a right click and select `New -> DOWRD (32-bit)`.
1. If prompted for the name, type `VirtualTerminalLevel` and click on `OK`.
1. Then double-click the newly created value (should be highlighted blue).
1. A new window should have popped up, asking you for the value.
1. Set the value to 1 and click OK.
1. You can now close this window.

_If this solved your problem, please remember to close the issue. If this solution didn't help, feel free to tell me!_

**Comment by lxgr-linux** [comment]
Normally this should be fixed by the `os.system("")` statement in the code, but this may be caused by the python from the microsoft store.

**Comment by Bambaclad1** [comment]
![image](https://user-images.githubusercontent.com/67043806/174110209-2a27dd9a-d90d-4c6e-82fc-33d063c558d0.png)
Its still occours, am i supposed to restart my laptop to let the changes make effect?

**Comment by lxgr-linux** [comment]
Try restarting.

**Comment by Bambaclad1** [comment]
It still looks like that, and if i press any keys like wasd most text will glitch and it will cut half of the screen.

**Comment by lxgr-linux** [comment]
have you tried the python that's not from the microsoft store?

**Comment by Bambaclad1** [comment]
I did, i got python from the site itself and removed the ms store one.

**Comment by Bambaclad1** [comment]
This is weird... I wanted to show some friends on my on school about this project but it works well... I'm gonna mess with the settings and see if it gets fixed and then tell you what fixed it.

**Comment by lxgr-linux** [comment]
That would be good to know.

**Comment by Bambaclad1** [comment]
Fixed it! I found the issue in use old console for cmd, this fricked up the game.
Incase you wanna know the fix,
Open commandprompt, Properties, Options and disable old commandprompt
![image](https://user-images.githubusercontent.com/67043806/174358894-d8904d15-7bd5-4420-aca2-d5968384f234.png)
which is the one called Veroudere Console...

**Comment by lxgr-linux** [comment]
That's very good to know, thanks for updating this!
