### ISSUE TITLE
Evolving Removes Shiny Status

### ISSUE THREAD

**Issue by digitalcontemplation** [lxgr-linux/pokete#163]
https://github.com/lxgr-linux/pokete/wiki/HowToPlay#shiny-poketes

**To Reproduce**
1. Have Shiny Pokete
2. Level up to evolve
3. No longer have Shiny status.

**Environment**
 - OS: macOS 12.4 21F79 arm64
 - Pokete version 0.7.2
 - Python version 3.9.13
 - Scrap engine version 1.2.0

**Comment by phaberest** [comment]
Sounds like the evolved pokete is in fact a new Poke instance where are kept the attacks the pokete has learned but the shiny status is lost. I'm not python fluent but I'd give it a try
