### ISSUE TITLE
Rebindable keys 

### ISSUE THREAD

**Issue by lxgr-linux** [lxgr-linux/pokete#167]
**Is your feature request related to a problem? Please describe.**
Rebindable keys should be added, since it was requested several times.

**Comment by magnus-ISU** [comment]
I'm motivated to work on this, since I use a different keyboard layout.
I can search for many places in the code with [ "'w'", "'a'", ... ]. It should be as easy as replacing these all with an array stored in the config object, right?

**Comment by lxgr-linux** [comment]
I would go with with not really an array, but rather an object with childs like `Key_up` or `Key_down`, because this might be more verbose. 
I would like to see how you would do it, in a PR.

**Comment by magnus-ISU** [comment]
The best way would be to make a function that detects if a certain type of input is pressed, and add logic to allow many keys to map to 1 input type. By default for example, `w`, `k`, `KEY_UP`, should all move up for example.

First I need to know some things.

How are settings stored? For example, I changed my character's symbol to `*`. Where is the code that handles that?

What actions are in the game? So far as I can tell, there is
 - Actions in combat `[1,2,3,4]`
   - Attacks in combat if you press 1 `[1,2,3,4]`
   - In any combat menu, there is also `[w,s,Enter]`
   - After a pokete perishes, `[y,n]`
 - Movement outside of combat `[w,a,s,d]`
 - Actions outside of combat `[1,2,3,4,5,6,?,e]`
 - Selecting things in menus `[w,s,Enter]`
 - Selecting things in a PokeCenter `[a,b,c]`
 - Exiting several menus and places: `[q, Escape]`

Are these all of them, or is there more?

It seems to me then that there are the following needed actions (keys in your dict):
 - up, down, left, right, select
 - Option_1 through Option_4 for menus like the attack menu.
 - Run, Inv, dEck, Pokedex, Clock, help?, Quit

**Comment by anakojm** [comment]
Hi, I think my fork might help you: [I changed the binding to work with azerty keyboards](https://github.com/anakojm/pokete-zqsd).

**Comment by lxgr-linux** [comment]
> How are settings stored? For example, I changed my character's symbol to *. Where is the code that handles that?

In pokete.py there is a function called `save()` and one that's called `read_safe`, which save/read a struct containing all relevant information to/from the savefile (~/.cache/pokete/pokete.json).
`read_save()` also contains default values for migration between versions.

I would go with an entry in this struct called `keys` and a class `Keys` which holds the different bindings as its attributes e.g. `keys.up`, `keys.down` ...
This class should implement the to_dict() and the from_dict() methods which just return a struct from which the keys can be reconstructed/reconstruct the keys object from such a dict.
This `keys` object from the `Keys` class then can also be used to implement a graphical way to change those keys in the settings menu.

> Are these all of them, or is there more?

I don't think there are more, but I personally would like to just have the movement, escape keys and "quick"-attacks (#178) rebindable.

**Comment by magnus-ISU** [comment]
I personally want all keys rebindable, for instance because my keyboard is not QWERTY. Maybe the others shouldn't be editable from in-game, but at least I'm migrating all hotkeys to use this different input method because the current way is hard to extend and requires a lot of duplicated logic everywhere and makes it impossible to know if these are all the inputs or not even.

**Comment by magnus-ISU** [comment]
Something like this is where I'm starting at, in `hotkeys.py`:

```
class Hotkey(Enum):
    LEFT = auto()
    RIGHT = auto()
    UP = auto()
    DOWN = auto()
    ACCEPT = auto()
    CANCEL = auto()

    RUN = auto()
    DECK = auto()
    INVENTORY = auto()
    POKEDEX = auto()
    MAP = auto()
    CLOCK = auto()
    HELP = auto()

    ACT_1 = auto()
    ACT_2 = auto()
    ACT_3 = auto()
    ACT_4 = auto()

hotkey_mappings = {
    'a':        Hotkey.LEFT
    'h':        Hotkey.LEFT
    'Key.LEFT': Hotkey.LEFT
    'd':         Hotkey.RIGHT,
    'l':         Hotkey.RIGHT,
    'Key.RIGHT': Hotkey.RIGHT
    'w':      Hotkey.UP,
    'k':      Hotkey.UP,
    'Key.UP': Hotkey.UP,
    's':        Hotkey.DOWN,
    'j':        Hotkey.DOWN,
    'Key.DOWN': Hotkey.DOWN,

    ' ':         Hotkey.ACCEPT,
    'Key.ENTER': Hotkey.ACCEPT,
    'y':         Hotkey.ACCEPT,
    'q':       Hotkey.CANCEL,
    'Key.ESC': Hotkey.CANCEL,
    'n':       Hotkey.CANCEL,

    'r': Hotkey.RUN,
    'e': Hotkey.DECK,
    'i': Hotkey.INVENTORY,
    'p': Hotkey.POKEDEX,
    'm': Hotkey.MAP,
    'c': Hotkey.CLOCK,
    '?': Hotkey.HELP,

    '1': Hotkey.ACT_1,
    '2': Hotkey.ACT_2,
    '3': Hotkey.ACT_3,
    '4': Hotkey.ACT_4,
}

def get_input() -> Hotkey:
    event = _ev()
    return hotkey_mappings[event]
```

I need to figure out what the actual names are for hotkey names, and trim the quotes off of event's return value, but it should be much clearer to use.
