### ISSUE TITLE
pipenv install pynput error

### ISSUE THREAD

**Issue by BaskerShu** [lxgr-linux/pokete#172]
**Checklist**
I have:
- [Y] Searched the Issues page for my problem/feature request
- [Y] Updated all related software and Pokete it self

**Describe the bug**
pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement pynput>=2.11 (from versions: 0.2, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8.1, 1.3.9, 1.3.10, 1.4, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6)

**To Reproduce**
1. run `pipenv install --dev`

**Expected behavior**
The pipenv environment is created successfully

**Screenshots**
<img width="753" alt="image" src="https://user-images.githubusercontent.com/21261458/174216863-1febcf7f-7ae4-4906-be34-6d622cd69acb.png">
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/21261458/174217780-689a925e-b1b8-4e18-87a1-f18e829d326f.png">

**Environment**
 - OS: [Macos 12.4]
 - Pokete version [latest]
 - Python version [3.10.5]

**Comment by ElixExe22** [comment]
Im not smart but i think you need to update pip

**Comment by lxgr-linux** [comment]
I don't know where this version came from, but it will be corrected in #171
