### ISSUE TITLE
Images are broken in wiki pages

### ISSUE THREAD

**Issue by phaberest** [lxgr-linux/pokete#173]
**Checklist**
I have:
- [x] Searched the Issues page for my problem/feature request
- [ ] Updated all related software and Pokete it self

**Describe the bug**
The images in wiki have relative paths instead of full urls [as indicated in GitHub's docs](https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#linking-to-images-in-a-repository)

**To Reproduce**
1. Go to [a wiki page](https://github.com/lxgr-linux/pokete/wiki/HowToPlay#fights)
2. See

**Screenshots**
![Screenshot 2022-06-17 at 11 38 35](https://user-images.githubusercontent.com/3464092/174283118-30d3eadd-ba59-47e5-bf48-0e60ba97cff9.JPG)

I don't have access to wiki editing, but the fix should be as easy as adding `https://github.com/lxgr-linux/pokete/blob/master` prefix to every image URL

**Comment by lxgr-linux** [comment]
Oh yes, I will do that.
