### ISSUE TITLE
Game crashes after entering your name and the initial conversation 

### ISSUE THREAD

**Issue by ryan-WORK** [lxgr-linux/pokete#176]
**Checklist**
I have:
- [ X ] Searched the Issues page for my problem/feature request
- [ X ] Updated all related software and Pokete it self

**Describe the bug**
After starting the game, entering my name, and and going through the initial conversation and error occurs dealing with `settings` in file `./pokete_classes/audio.py` line 16

**To Reproduce**
1. Clone repo
2. create venv & install deps
3. run `python pokete.py`
4. Enter name
5. Go through intro conversation
6. See error
```
--R--o-----------------------------------------------------------------------------------------------------------------------------------------1: Deck  2: Exit  3: Map  4: Inv.  5: Dex  6: Clock  ?: Help                                                                                   
Process Process-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rcarl/Projects/pokete/pokete_classes/audio.py", line 16, in audio_fn
    while settings("audio").val:
  File "/Users/rcarl/Projects/pokete/pokete_classes/settings.py", line 68, in __call__
    return [i for i in self.settings if i.name == name][0]
IndexError: list index out of range
```

**Expected behavior**
Expect game to proceed as normal

**Environment**
 - OS: macos
 - Pokete version 0.7.2
 - Python version 3.8
 - Scrap engine version [e.g. 1.1.0]

**Additional context**

**Comment by lxgr-linux** [comment]
Hello, that's pretty interesting.
Did you use pipenv?

**Comment by lxgr-linux** [comment]
I can't reproduce, can you verify your on the newest version?

**Comment by magnus-ISU** [comment]
It's possible this is a multithreading/concurrency problem maybe? Is the audio initialized on a separate thread, at the same time as the settings object?

**Comment by lxgr-linux** [comment]
It can't be, because the settings object is initialized way before any audio is even started.

**Comment by lxgr-linux** [comment]
Are you sure you're not on an old commit?
