### ISSUE TITLE
Feature request: Better information about what attacks do.

### ISSUE THREAD

**Issue by magnus-ISU** [lxgr-linux/pokete#179]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have no idea what polish does as a new player.

**Describe the solution you'd like**
Tell me what it does.
I see its in the deck, but the flavor text should note it too after using the power, or you should be able to see your buffs somehow or something.

**Comment by malnjayz** [comment]
Sounds nice, I already hava an idea on how to implement that. I'll be back with a PR shortly.
