### ISSUE TITLE
Adding support for multi-language

### ISSUE THREAD

**Issue by 0lbap** [lxgr-linux/pokete#185]
Hi !
I suggest to separate dialogs from python files, something like `/lang/en.yml` (or other format like json).
That could be usefull to translate the game in other languages.
Have a nice day !

**Comment by Tyson453** [comment]
I'll get to work changing all of the pokete data to json. Shouldn't take too long.

**Comment by lxgr-linux** [comment]
Multi language support is something very problematic to add, because the game heavily relies on some strings being exactly as long, as they are, for example the minimum supported terminal size is backed by exactly that.

Also scrap_engine has some problems with non monospace characters.
