### ISSUE TITLE
Tried to boot, just got this

### ISSUE THREAD

**Issue by Ilovetoocode** [lxgr-linux/pokete#190]
File "pokete.py", line 89
SyntaxError: Non-ASCII character '\xc3' in file pokete.py on line 89, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
What went wrong?

**Comment by magnus-ISU** [comment]
That's strange, it works fine for me. Did you download from github?

If so, what is in file pokete.py at line 89? Is it the same as [here?](https://github.com/lxgr-linux/pokete/blob/master/pokete.py)

**Comment by lxgr-linux** [comment]
Hello, it may be because of the "ü". But what pythonversion are you on?

**Comment by Ilovetoocode** [comment]
Latest verion of 3

**Comment by Ilovetoocode** [comment]
> That's strange, it works fine for me. Did you download from github?
> 
> If so, what is in file pokete.py at line 89? Is it the same as [here?](https://github.com/lxgr-linux/pokete/blob/master/pokete.py)

I did, and the line is the same

**Comment by lxgr-linux** [comment]
> Latest verion of 3

That means 3.10?
And what operating system?

**Comment by Ilovetoocode** [comment]
3.8, although, I do need to now test something.... I got it on Linux Mint, and so that means I might have to run python3 as a command. Cause, for some godforsaken reason, when I installed it on APT from the repo... I got both a version of python3, AND a version of python 2

**Comment by Ilovetoocode** [comment]
AAAND, this is what happened: 
python3 pokete.py
Traceback (most recent call last):
  File "pokete.py", line 19, in <module>
    import scrap_engine as se
ModuleNotFoundError: No module named 'scrap_engine'

**Comment by Tyson453** [comment]
In the README file under installation, it tells you all the modules you need to install. Make sure all of those are installed and it should run.

**Comment by magnus-ISU** [comment]
Perhaps the README should say something like:

```
# pip install scrap_engine playsound pygobject
$ git clone https://github.com/lxgr-linux/pokete.git
$ cd pokete; pip3 install whatever-the-command-is
$ ./pokete/pokete.py
```
under installation? Currently it gives the impression there are no required libraries, I agree with @Ilovetoocode

**Comment by lxgr-linux** [comment]
The `#` was intended to signal, that this command may be run by root. But since root privileges are not required to install python packages, at least locally, this can be changed to a `$`.

**Comment by Ilovetoocode** [comment]
Thank  you all! It works now!
