### ISSUE TITLE
Trainer battles should not allow you to stop the fight halfway through

### ISSUE THREAD

**Issue by magnus-ISU** [lxgr-linux/pokete#192]
**Is your feature request related to a problem? Please describe.**
Currently, you're able to have 2 poketes, have one of them die fighting a trainer, leave the fight, and continue on (walking past the trainer, among other issues)

**Describe the solution you'd like**
You don't have the option to not select another pokete when battling a trainer.

**Comment by lxgr-linux** [comment]
That's true, I didn't think of this when I implemented it.
