### ISSUE TITLE
People who have dialogue which activates persistently (notably, deepest forest trainer guy who welcomes you in) are annoying

### ISSUE THREAD

**Issue by magnus-ISU** [lxgr-linux/pokete#198]
They stop you every time you go by, and you have to mash keys to get them to leave you alone.

They should instead only initiate conversations after the first time if you try to move into them.

**Comment by lxgr-linux** [comment]
That's something I got told several times, some NPCs loose their initiative after talking/fighting/trading with them, but I wanted to keep the initiative for classical NPCs, so you can walk back to them after missing some important information. I would suggest moving the most annoying NPCs out of the way and make the Arena instructors loose their initiative after completing the arena.
