### ISSUE TITLE
Freeze the terminal screen

### ISSUE THREAD

**Issue by Deicide68** [lxgr-linux/pokete#217]
Is it able to freeze the terminal screen and not allow to input after switching screen?

The current terminal still can detect key input although I have switched and typed on another screen.

os: Window 10

**Comment by lxgr-linux** [comment]
Hey,
that's because of how input on windows at least, is handled, which is based in pynput, which always grabs keyboard input.

I will set up a windows vm soon to test if the better input method used on linux may also work on windows.
