### ISSUE TITLE
Statistics for owned Poketes

### ISSUE THREAD

**Issue by ondrejmyska** [lxgr-linux/pokete#239]
**Describe the solution you'd like**
I would like to discuss idea of implementing statistics for Poketes. Let's imagine you can track interesting data about your Pokete

- Datetime of ownership
- Datetime when Pokete was evolved
- Total battles
- Win/loss statistic
- Total earn XP
- any others?

UI proposal:
Introduce new action 3: Stats in details page with popup similar to the Nature popup.
![obrazek](https://user-images.githubusercontent.com/5269369/185906403-ae740902-8304-4390-9493-6549d2d9ed72.png)

What do you think about that?

**Comment by lxgr-linux** [comment]
That's a very good idea,

> Total earn XP

I guess this is somehow already shown via the current level.
I also think it would be nice to show the ball the pokete was caught with (superball, hyperball, poketeball ...)

> UI proposal:
Introduce new action 3: Stats in details page with popup similar to the Nature popup.
![image](https://user-images.githubusercontent.com/64218491/185947011-04de90bf-6b10-478a-89f4-746eb11800ec.png)

Then extra actions have to be moved to the 4.

I really like the idea, do you want to program it?

**Comment by MaFeLP** [comment]
> > Total earn XP
> 
> I guess this is somehow already shown via the current level.

It actually is not, as poketes are not caught with `XP=0`. Therefore, the level does not represent how much the pokete has acquired **with the player**. I think it would be therefore more interesting.

Also, looking at how much each individual attack has been used could lead to interesting statistics: Which pokete is used by the player to level other poketes (low gained XP, but high attack usage) etc.

**Comment by lxgr-linux** [comment]
> > > Total earn XP
> > 
> > 
> > I guess this is somehow already shown via the current level.
> 
> It actually is not, as poketes are not caught with `XP=0`. Therefore, the level does not represent how much the pokete has acquired **with the player**. I think it would be therefore more interesting.

Yes, if that's what they meant.

> 
> > * any others?
> 
> Also, looking at how much each individual attack has been used could lead to interesting statistics: Which pokete is used by the player to level other poketes (low gained XP, but high attack usage) etc.

That's very valuable for nerving and buffing attacks or poketes.

**Comment by ondrejmyska** [comment]
Ok guys, thank you for feedback. I'll implement the feature
