### ISSUE TITLE
[FR] Fight enhancements

### ISSUE THREAD

**Issue by ondrejmyska** [lxgr-linux/pokete#246]
I am thinking about enhancement of information which are available during fight which could help player to bring more appropriate tactic to the fight. 
1) Player cannot see any visual highlight of Pokete type (player and enemy). Pokete type is visualized in Pokedex, but not directly in fight
2) No information about effective/ineffective status against enemy (Fire vs Watter type)
3) Pokete statistics (player and enemy??) can be affected by special abilities of attack like Polish, but player cannot see it. 

What do you think? I can try to implement it.

**Comment by lxgr-linux** [comment]
> 1. Player cannot see any visual highlight of Pokete type (player and enemy). Pokete type is visualized in Pokedex, but not directly in fight

How could I have been so stupid forgetting about this. Yes, that's a very good idea.

> 2. No information about effective/ineffective status against enemy (Fire vs Watter type)

I wouldn't do that, because that's a think I don't like about the newer pokemon games.

> 3. Pokete statistics (player and enemy??) can be affected by special abilities of attack like Polish, but player cannot see it.

I would just make the passive attacks more verbose, so that you directly get a feedback on what just happenend.
