### ISSUE TITLE
What is scrap_engine

### ISSUE THREAD

**Issue by Hamster-lord** [lxgr-linux/pokete#256]

**Comment by Hamster-lord** [comment]
Why can't I get scrap_engine

**Comment by malnjayz** [comment]
scrap_engine is an engine for games in the cli, made by @lxgr-linux. You can check out the repo here: https://github.com/lxgr-linux/scrap_engine You should be able to install it using pip.

`pip install scrap_engine`

If that doesn't work you can post you're pip-logs here, maybe we can figure that out.
