### ISSUE TITLE
AttributeError: module 'scrap_engine' has no attribute 'screen_height'

### ISSUE THREAD

**Issue by asdfghjkl403622** [lxgr-linux/pokete#272]
**Checklist**
I have:
- [ X] Searched the Issues page for my problem/feature request
- [ X] Updated all related software and Pokete it self

**Describe the bug**
I have tried to start pokete after installing scrap engine and ran into this issue

**To Reproduce**
1. install scrap engine using pip3
2. ./pokete.py
3. error

**Expected behavior**
game starts

**Screenshots**

**Environment**
 - OS: Macos Monterey
 - Pokete version 1.9.1
 - Python version Python 3.11.5
 - Scrap engine version 0.1.0

**Additional context**

**Comment by lxgr-linux** [comment]
Hey there,
are you sure, you're on the latest scrap_engine version?
Because latest is 1.4.0.

Cheers

**Comment by asdfghjkl403622** [comment]
I installed the latest version available on pip on macos, and that's the version it installed. Should I attempt a manual install?

**Comment by lxgr-linux** [comment]
try to install it again, it should be 1.4.0

**Comment by asdfghjkl403622** [comment]
`% pip3 install --upgrade scrap-engine
Requirement already satisfied: scrap-engine in /Users/90307528/homebrew/lib/python3.11/site-packages (0.1.0)
Collecting scrap-engine
  Using cached scrap_engine-1.4.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/9b/ad/eb8e100615f865f2752f93593a0da47dec0e00cda60d8b61559cd631c9b9/scrap_engine-1.4.0.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/9b/ad/eb8e100615f865f2752f93593a0da47dec0e00cda60d8b61559cd631c9b9/scrap_engine-1.4.0.tar.gz has inconsistent version: expected '1.4.0', but metadata has '0.1.1'
  Using cached scrap_engine-1.3.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/1a/8f/80fa72313a15b9e76648d20c8ed53a57222d7b7bde69bb92a9251cfc76e3/scrap_engine-1.3.0.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/1a/8f/80fa72313a15b9e76648d20c8ed53a57222d7b7bde69bb92a9251cfc76e3/scrap_engine-1.3.0.tar.gz has inconsistent version: expected '1.3.0', but metadata has '0.1.1'
  Using cached scrap_engine-1.2.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/3e/d6/b51ae9c311603c76e952a39baabca3c81887e4609f7bf7308c2e19ac8c9f/scrap_engine-1.2.0.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/3e/d6/b51ae9c311603c76e952a39baabca3c81887e4609f7bf7308c2e19ac8c9f/scrap_engine-1.2.0.tar.gz has inconsistent version: expected '1.2.0', but metadata has '0.1.1'
  Using cached scrap_engine-1.1.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/69/da/7fd844e706df31be26f16778f93a823cda4ef70b4494a2044b71e4c41a0e/scrap_engine-1.1.0.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/69/da/7fd844e706df31be26f16778f93a823cda4ef70b4494a2044b71e4c41a0e/scrap_engine-1.1.0.tar.gz has inconsistent version: expected '1.1.0', but metadata has '0.1.1'
  Using cached scrap_engine-1.0.1.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/50/96/b981beb522e04c05faba7fffb4a332979048d3343db444e3e393352e959c/scrap_engine-1.0.1.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/50/96/b981beb522e04c05faba7fffb4a332979048d3343db444e3e393352e959c/scrap_engine-1.0.1.tar.gz has inconsistent version: expected '1.0.1', but metadata has '0.1.1'
  Using cached scrap_engine-1.0.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/7f/19/efda9d670bd0692595e6251d7c4df75498d4a1844273cac2dddaec49f898/scrap_engine-1.0.0.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/7f/19/efda9d670bd0692595e6251d7c4df75498d4a1844273cac2dddaec49f898/scrap_engine-1.0.0.tar.gz has inconsistent version: expected '1.0.0', but metadata has '0.1.1'
  Using cached scrap_engine-0.3.3.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/3e/30/628214ea97676feb07afb5cb63decdb996dd421ce007c23d58b8cf4c3d5e/scrap_engine-0.3.3.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/3e/30/628214ea97676feb07afb5cb63decdb996dd421ce007c23d58b8cf4c3d5e/scrap_engine-0.3.3.tar.gz has inconsistent version: expected '0.3.3', but metadata has '0.1.1'
  Using cached scrap_engine-0.3.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/05/75/be4d25d2e411386e8a8f991afa96c7d7203c76b971100954727e60ba8251/scrap_engine-0.3.2.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/05/75/be4d25d2e411386e8a8f991afa96c7d7203c76b971100954727e60ba8251/scrap_engine-0.3.2.tar.gz has inconsistent version: expected '0.3.2', but metadata has '0.1.1'
  Using cached scrap_engine-0.3.1.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/01/da/6a52e2c572aa2ea3bfc4c4aefc120ad1d151b63db295d2bf96a6cc221db1/scrap_engine-0.3.1.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/01/da/6a52e2c572aa2ea3bfc4c4aefc120ad1d151b63db295d2bf96a6cc221db1/scrap_engine-0.3.1.tar.gz has inconsistent version: expected '0.3.1', but metadata has '0.1.1'
  Using cached scrap_engine-0.3.0.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/e9/2d/06d470c291946f30310ffce89ff83ea5e549c661c631e1f5f11d26cad678/scrap_engine-0.3.0.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/e9/2d/06d470c291946f30310ffce89ff83ea5e549c661c631e1f5f11d26cad678/scrap_engine-0.3.0.tar.gz has inconsistent version: expected '0.3.0', but metadata has '0.1.1'
  Using cached scrap_engine-0.2.1.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/52/7d/5ef99a3503f0608c01f62caadf66c067a0021115ba7de5b92b754b44d51a/scrap_engine-0.2.1.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/52/7d/5ef99a3503f0608c01f62caadf66c067a0021115ba7de5b92b754b44d51a/scrap_engine-0.2.1.tar.gz has inconsistent version: expected '0.2.1', but metadata has '0.1.1'
  Using cached scrap_engine-0.2.0.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/9f/94/3fb51a0402a2fb6cbda1728ee2938453ebd1ea450547da33c3938da56bda/scrap_engine-0.2.0.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/9f/94/3fb51a0402a2fb6cbda1728ee2938453ebd1ea450547da33c3938da56bda/scrap_engine-0.2.0.tar.gz has inconsistent version: expected '0.2.0', but metadata has '0.1.1'
  Using cached scrap_engine-0.1.3.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/d0/28/7bc124bd21393b8048f203686ab2ee8d00465cc7475d0bdbf9c937e87a76/scrap_engine-0.1.3.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/d0/28/7bc124bd21393b8048f203686ab2ee8d00465cc7475d0bdbf9c937e87a76/scrap_engine-0.1.3.tar.gz has inconsistent version: expected '0.1.3', but metadata has '0.1.1'
  Using cached scrap_engine-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/4c/52/49abd53cd53b738cf95bdd2fb1741aa1c40e63c4fc6e064c4d90d21f1e2f/scrap_engine-0.1.2.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/4c/52/49abd53cd53b738cf95bdd2fb1741aa1c40e63c4fc6e064c4d90d21f1e2f/scrap_engine-0.1.2.tar.gz has inconsistent version: expected '0.1.2', but metadata has '0.1.1'
  Using cached scrap_engine-0.1.1.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/c3/fc/2cdfc34b15712bf203185042c9c810b77f0a0468c8002620f35de296eff7/scrap_engine-0.1.1.tar.gz (from https://pypi.org/simple/scrap-engine/) (requires-python:>=3): Requested scrap-engine from https://files.pythonhosted.org/packages/c3/fc/2cdfc34b15712bf203185042c9c810b77f0a0468c8002620f35de296eff7/scrap_engine-0.1.1.tar.gz has inconsistent version: expected '0.1.1', but metadata has '0.1.0'
`

**Comment by lxgr-linux** [comment]
Ah yes, I will look into this

**Comment by lxgr-linux** [comment]
please try again, this problem should be fixed now.
Cheers
