### ISSUE TITLE
Improved Roadmap

### ISSUE THREAD

**Issue by JanekKermit** [lxgr-linux/pokete#275]
**Is your feature request related to a problem? Please describe.**
Current roadmap is small, not detailed and not intuitive for new players 

**Describe the solution you'd like**
Make it larger, more detailed, colorful and easier to read.
Concept art:
![obraz](https://github.com/lxgr-linux/pokete/assets/44294151/c4899e38-a8fe-4678-a361-cdb157d1fcf5)

**Additional context**
I'm open to suggestions and changes, so if you don't like my concept, feel free to point it out

**Comment by lxgr-linux** [comment]
I think that's a great idea, like pointed out via discord I would:
- Keep the size of the roadmap smaller than proposed, to keep the door open for further expansion, but also significantly bigger, then what is currently implemented
- The w,a,s,d,<enter> navigation and detailview should also be kept
- Map should still be changeable via the dictionary modifications, similar to what is happening rn. to avoid hardcoding stuff

This would definitely make a great addition, feel free to open a PR.
What do you thing @MaFeLP?
